name: Deploy Telegram Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонирование репозитория
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Установка SSH-соединения
    - name: Set up SSH connection
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.BOT_KEY }}

    - name: Set permissions for atom
      run: |
        ssh -o StrictHostKeyChecking=no atom@${{ secrets.SERVER_IP }} "
          chown -R atom:developers /home/atom/gptHelpBot &&
          chmod -R 775 /home/atom/gptHelpBot
        "

    # 3. Копирование кода на сервер
    - name: Upload code to VPS
      run: |
        scp -o StrictHostKeyChecking=no -r * atom@${{ secrets.SERVER_IP }}:/home/atom/gptHelpBot

    # 4. Сборка Docker-образа на сервере
    - name: Build and run Docker container on VPS
      run: |
        ssh -o StrictHostKeyChecking=no atom@${{ secrets.SERVER_IP }} "
          cd /home/atom/gptHelpBot &&
          docker build -t bothelp . &&
          docker stop bothelp || true &&
          docker rm bothelp || true &&
          docker run -d \
            --name bothelp \
            -e TOKEN_BOT=${{ secrets.TOKEN_BOT }} \
            -e TOKEN_AI=${{ secrets.TOKEN_AI }} \
            -e USERS=${{ secrets.USERS }} \
            -p 3000:3000 helpbot
        "
